### ISSUE TITLE
Can't compile Titles, shows that SMJansson has reserved keyword

### ISSUE THREAD

**Issue by iphonerestore** [thraaawn/SMJansson#5]
'in' is a newly reserved keyword that may be used in the future; use a different name as an identifier

**Comment by thraaawn** [comment]
I have no idea what you are talking about. Elaborate please.

**Comment by iphonerestore** [comment]
Hey Thrawn, 

So to be precise, I am trying to recompile the Titles plugin using MoreColors because the current color system compiled with the Titles plugin is broken.

However, in order for me to compile the pre requisite is SMJansson 2.6 which is what I have. Now when I compile the titles plugin with SMJansson for some reason its throwing a reserved word error and the following issue is posted above as those were the exact words printed by the compiler. 

The compiler failed to compile and so I wanted you to know that the error above is causing issues. I am more than happy to recompile and show you the console output for the compiler.

**Comment by thraaawn** [comment]
For SourceMod 1.7 compatibility you'll need to use the inc provided in [this](https://forums.alliedmods.net/showpost.php?p=2268546&postcount=49) post.
